// app/api/generate-one-take-prompt/route.ts
//
// UPDATED: now imports the shared human-realism-system helper instead of
// reading its own local realism-details.md. This file REPLACES the
// version from the earlier one-take-ugc package — if you already uploaded
// that one, overwrite it with this version, and delete
// lib/prompt-skills/one-take-ugc/references/realism-details.md since it's
// now superseded by lib/realism.ts + lib/prompt-skills/human-realism-system/.
//
// Generates a One-Take UGC realism prompt: single unbroken phone-camera
// take, locked verbatim dialogue, fixed camera geometry, second-by-second
// choreography.
//
// This is exposed in SceneBloc as ONE option inside the Cinema Gear 2.0
// movement picker ("One-Take Locked (UGC realism)") — not a separate mode.
// When this movement is selected, this route's dialogue generation
// REPLACES the Voiceover Scripts step for that generation, since dialogue
// and choreography are fused here and cannot be generated by a separate
// pass without producing two conflicting timing layers.

import { NextRequest, NextResponse } from "next/server";
import { readFile } from "fs/promises";
import path from "path";
import Anthropic from "@anthropic-ai/sdk";
import { buildRealismContext, type RealismTag, type RealismProfileKey } from "@/lib/realism";

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

const SKILL_DIR = path.join(process.cwd(), "lib/prompt-skills/one-take-ugc");

interface RequestBody {
  durationSeconds?: number;
  aspectRatio?: string;
  setting: string;
  reflectiveSurface?: "mirror" | "window" | "none";
  cameraOffsetSide?: "left" | "right";
  backgroundElements?: string[];
  heroPropContainer?: string;
  lightingPreset?: string;
  accent?: string;
  wordsPerSecond?: number;
  toneTags?: string[];
  propArc?: { name: string; materialDetail?: string }[];
  realismProfile?: RealismProfileKey; // defaults to "ugc-raw" — this skill IS the UGC genre, but any profile can override
  realismTags?: RealismTag[];        // optional extra tags on top of the profile default
  realismPeakTimestamps?: number[];  // optional — if omitted, model infers proximity peaks from its own choreography
  ctaBrief?: string;
  brief: string;
  additionalNotes?: string;
}

export async function POST(req: NextRequest) {
  try {
    const body: RequestBody = await req.json();

    if (!body.brief?.trim() || !body.setting?.trim()) {
      return NextResponse.json(
        { error: "brief and setting are required" },
        { status: 400 }
      );
    }

    const skillMd = await readFile(path.join(SKILL_DIR, "SKILL.md"), "utf-8");

    // Pull realism context from the SHARED system, not a local file.
    // Defaults to "ugc-raw" since that's the genre this skill serves —
    // callers can override to "luxury-editorial" or "commercial-polished"
    // if a one-take-style shot is being used for higher-end content.
    const realismContext = buildRealismContext({
      profile: body.realismProfile ?? "ugc-raw",
      tags: body.realismTags ?? [],
      peakTimestamps: body.realismPeakTimestamps,
    });

    const duration = body.durationSeconds ?? 30;
    const wps = body.wordsPerSecond ?? 3.4;

    const systemPrompt = `
You are generating a One-Take UGC realism video prompt using the skill
below. Follow the Mandatory Prompt Structure exactly — all 8 sections, in
order, with the FIXED clauses inserted verbatim (do not paraphrase them).
Output only the final paste-ready prompt. No preamble, no explanation.

---

SKILL:

${skillMd}

${realismContext ? `---\n\n${realismContext}` : ""}
`.trim();

    const userMessage = `
Generate a One-Take UGC prompt for the following brief.

BRIEF: ${body.brief}
SETTING: ${body.setting}
DURATION: ${duration}s
ASPECT RATIO: ${body.aspectRatio ?? "Horizontal 16:9 landscape"}
REFLECTIVE SURFACE: ${body.reflectiveSurface ?? "mirror"}
CAMERA OFFSET SIDE: ${body.cameraOffsetSide ?? "left"}
${body.backgroundElements?.length ? `BACKGROUND ELEMENTS: ${body.backgroundElements.join(", ")}` : ""}
${body.heroPropContainer ? `HERO PROP CONTAINER: ${body.heroPropContainer}` : ""}
${body.lightingPreset ? `LIGHTING: ${body.lightingPreset}` : ""}
${body.accent ? `ACCENT: ${body.accent}` : ""}
WORDS PER SECOND: ${wps}
${body.toneTags?.length ? `TONE: ${body.toneTags.join(", ")}` : ""}
${
  body.propArc?.length
    ? `PROP ARC (in order): ${body.propArc
        .map((p) => `${p.name}${p.materialDetail ? ` (${p.materialDetail})` : ""}`)
        .join(" -> ")}`
    : ""
}
${body.ctaBrief ? `CTA SHOULD SAY: ${body.ctaBrief}` : ""}
${body.additionalNotes ? `ADDITIONAL NOTES: ${body.additionalNotes}` : ""}

Generate all 6 dialogue lines with realistic timestamps sized to the
duration and words-per-second above. Generate the full choreography in
section 8 as sequential timestamped blocks covering the entire duration.
${realismContext ? "Weight realism detail toward the proximity-peak moments noted above." : ""}
Output only the final prompt.
`.trim();

    const response = await anthropic.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 3000,
      system: systemPrompt,
      messages: [{ role: "user", content: userMessage }],
    });

    const textBlock = response.content.find((c) => c.type === "text");
    const generatedPrompt = textBlock?.type === "text" ? textBlock.text : "";

    if (!generatedPrompt) {
      return NextResponse.json(
        { error: "Model returned no text content" },
        { status: 502 }
      );
    }

    return NextResponse.json({ durationSeconds: duration, prompt: generatedPrompt });
  } catch (err) {
    console.error("generate-one-take-prompt error:", err);
    return NextResponse.json(
      { error: "Failed to generate prompt" },
      { status: 500 }
    );
  }
}
